version: "3.4"
services:
  minio:
#    image: datashield/minio:ci
    image: minio/minio:RELEASE.2022-07-26T00-53-03Z
    ports:
      - 9000:9000
    environment:
      MINIO_ROOT_USER: molgenis
      MINIO_ROOT_PASSWORD: molgenis
#      MINIO_SERVER_URL: http://127.0.0.1:9000
#      MINIO_ACCESS_KEY: molgenis
#      MINIO_SECRET_KEY: molgenis
    command: server /data
  armadillo:
    image: molgenis/armadillo:2.2.3
    environment:
      SPRING_PROFILES_ACTIVE: development,docker-compose
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: molgenis
      MINIO_SECRET_KEY: molgenis
      RSERVE_HOST: rserver
      LOGGING_CONFIG: 'classpath:logback-file.xml'
      AUDIT_LOG_PATH: '/app/logs/audit.log'
#      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: 'https://auth.molgenis.org'
#      SPRING_SECURITY_OAUTH2_RESOURCESERVER_OPAQUETOKEN_CLIENT_ID: 'b396233b-cdb2-449e-ac5c-a0d28b38f791'
      DATASHIELD_WHITELIST: dsBase,dsDanger,resourcer
    ports:
      - 8080:8080
  rserver:
    image: datashield/armadillo-rserver:6.2.1-dev
    environment:
      DEBUG: "FALSE"
    ports:
      - 6311:6311
